name: Deploy (Backend + Frontend)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy Backend & Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Configurar Azure FunctionApp y conexión a BD
      - name: Configure Function App Settings
        run: |
          az functionapp config appsettings set --resource-group upt-arg-280 --name upt-afn-280 \
            --settings FUNCTIONS_INPROC_NET8_ENABLED=1

          az webapp config connection-string set --resource-group upt-arg-280 --name upt-afn-280 \
            --connection-string-type SQLAzure \
            --settings ShortenDB='Server=upt-dbs-280.database.windows.net;Database=shorten;User Id=adminsql;Password=upt.2025;TrustServerCertificate=True;'


      # ✅ Publicar y desplegar Backend (Azure Functions)
      - name: Publish Backend
        run: |
          cd src/ShortenFunction
          dotnet publish -c Release -o publish
          cd publish
          zip -r functionapp.zip .
          az functionapp deployment source config-zip -g upt-arg-280 -n upt-afn-280 --src functionapp.zip --verbose

      # ✅ Publicar y desplegar Frontend (Azure Static Web Apps)
      - name: Publish Frontend
        run: |
          cd src/ShortenApp
          npm install
          npm run build
          swa deploy ./dist -n upt-swa-280 --env production
