name: Security Scan (SonarCloud & Semgrep)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Run SonarCloud & Semgrep Scans
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=Vela2001
            -Dsonar.projectKey=ideaterraform2
            -Dsonar.sources=.
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.host.url=https://sonarcloud.io

      - name: Install & Run Semgrep
        run: |
          pip install semgrep
          semgrep --config=auto --json > semgrep-results.json || true

      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v4
        with:
          name: sonarcloud-report
          path: .scannerwork/

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.json
